import { PERMISSIONS } from "./permissions";
import { ROLES, type Role } from "./roles";

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  [ROLES.SYSTEM_OWNER]: ["*"],

  [ROLES.ADMIN]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_INVITE,

    PERMISSIONS.MEAL_PREFERENCE_UPDATE,
    PERMISSIONS.MEAL_PREFERENCE_VIEW,

    PERMISSIONS.MEAL_SESSION_VIEW,
    PERMISSIONS.MEAL_SESSION_CREATE,
    PERMISSIONS.MEAL_SESSION_UPDATE,
    PERMISSIONS.MEAL_SESSION_CLOSE,

    PERMISSIONS.MEAL_ENTRY_VIEW,
    PERMISSIONS.MEAL_ENTRY_CREATE,
    PERMISSIONS.MEAL_ENTRY_UPDATE,

    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_DELETE,

    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_UPDATE,

    PERMISSIONS.CALCULATION_VIEW,
    PERMISSIONS.CALCULATION_RUN,

    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,

    PERMISSIONS.SUBSCRIPTION_VIEW,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.MEAL_PREFERENCE_UPDATE,
    PERMISSIONS.MEAL_PREFERENCE_VIEW,

    PERMISSIONS.MEAL_SESSION_VIEW,
    PERMISSIONS.MEAL_SESSION_CREATE,
    PERMISSIONS.MEAL_SESSION_UPDATE,

    PERMISSIONS.MEAL_ENTRY_VIEW,
    PERMISSIONS.MEAL_ENTRY_CREATE,
    PERMISSIONS.MEAL_ENTRY_UPDATE,

    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_UPDATE,

    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_UPDATE,

    PERMISSIONS.CALCULATION_VIEW,
    PERMISSIONS.CALCULATION_RUN,

    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.MEAL_ENTRY_VIEW,
    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.CALCULATION_VIEW,
    PERMISSIONS.MEAL_PREFERENCE_UPDATE,
    PERMISSIONS.MEAL_PREFERENCE_VIEW,
  ],

  [ROLES.MESS_MALIK]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_INVITE,

    PERMISSIONS.MEAL_SESSION_VIEW,
    PERMISSIONS.MEAL_SESSION_CREATE,

    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_CREATE,

    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.DEPOSIT_CREATE,
  ],
};
