import { PERMISSIONS } from "./permissions";
import { ROLES, type Role } from "./roles";

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  [ROLES.SYSTEM_OWNER]: ["*"],

  [ROLES.ADMIN]: [
    // user
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_INVITE,

    // meal preference
    PERMISSIONS.MEAL_PREFERENCE_UPDATE,
    PERMISSIONS.MEAL_PREFERENCE_VIEW,

    // meal session
    PERMISSIONS.MEAL_SESSION_VIEW,

    // meal entry
    PERMISSIONS.MEAL_ENTRY_VIEW,
    PERMISSIONS.MEAL_ENTRY_CREATE,
    PERMISSIONS.MEAL_ENTRY_UPDATE,

    // expense
    PERMISSIONS.EXPENSE_VIEW,

    // deposit
    PERMISSIONS.DEPOSIT_VIEW,

    // calculation
    PERMISSIONS.CALCULATION_VIEW,
    PERMISSIONS.CALCULATION_RUN,

    // notification
    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE,

    // setting
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.MEAL_SETTING_VIEW,

    // subcripton
    PERMISSIONS.SUBSCRIPTION_VIEW,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
  ],

  [ROLES.MANAGER]: [
    // user
    PERMISSIONS.USER_VIEW,

    // meal preference
    PERMISSIONS.MEAL_PREFERENCE_UPDATE,
    PERMISSIONS.MEAL_PREFERENCE_VIEW,

    // meal session
    PERMISSIONS.MEAL_SESSION_VIEW,
    PERMISSIONS.MEAL_SESSION_OPEN,
    PERMISSIONS.MEAL_SESSION_CLOSE,
    PERMISSIONS.MEAL_SESSION_UPDATE,

    // mela entry
    PERMISSIONS.MEAL_ENTRY_VIEW,
    PERMISSIONS.MEAL_ENTRY_CREATE,
    PERMISSIONS.MEAL_ENTRY_UPDATE,

    // meal setting
    PERMISSIONS.MEAL_SETTING_VIEW,
    PERMISSIONS.MEAL_SETTING_CREATE,
    PERMISSIONS.MEAL_SETTING_UPDATE,
    PERMISSIONS.MEAL_SETTING_DELETE,

    // expense
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_DELETE,

    // deposit
    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.DEPOSIT_CREATE,
    PERMISSIONS.DEPOSIT_UPDATE,
    PERMISSIONS.DEPOSIT_DELETE,

    // claculation
    PERMISSIONS.CALCULATION_VIEW,
    PERMISSIONS.CALCULATION_RUN,

    // notice
    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.MEAL_ENTRY_VIEW,
    PERMISSIONS.MEAL_SESSION_VIEW,
    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.CALCULATION_VIEW,
    PERMISSIONS.MEAL_PREFERENCE_UPDATE,
    PERMISSIONS.MEAL_PREFERENCE_VIEW,
    PERMISSIONS.MEAL_SETTING_VIEW,
  ],

  [ROLES.MESS_MALIK]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_INVITE,

    PERMISSIONS.MEAL_SESSION_VIEW,

    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_CREATE,

    PERMISSIONS.DEPOSIT_VIEW,
    PERMISSIONS.DEPOSIT_CREATE,
  ],
};
